/*
 * This source file was generated by the Gradle 'init' task
 */
package board.dio;

import board.dio.persistence.migration.MigrationStrategy;
import board.dio.ui.MainMenu;

import static board.dio.persistence.config.ConnectionConfig.getConnection;

import java.sql.SQLException;

public class App {

    public static void main(String[] args) throws SQLException {
        try (var connection = getConnection()) {
            new MigrationStrategy().executeMigration();
        }
        new MainMenu().execute();
    }
}
